apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
  name: eap-with-helm
  annotations:
    include.release.openshift.io/ibm-cloud-managed: 'true'
    include.release.openshift.io/self-managed-high-availability: 'true'
    include.release.openshift.io/single-node-developer: 'true'
    capability.openshift.io/name: Console
spec:
  description: 'Deploy a JBoss EAP 7 application using a Helm Chart.'
  displayName: Get started with JBoss EAP 7 using a Helm Chart
  durationMinutes: 10
  icon: >-
    data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2Q3MWUwMDt9LmNscy0ye2ZpbGw6I2MyMWEwMDt9LmNscy0ze2ZpbGw6I2NkY2RjZDt9LmNscy00e2ZpbGw6I2I3YjdiNzt9LmNscy01e2ZpbGw6I2VhZWFlYTt9LmNscy02e2ZpbGw6I2ZmZjt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPkxvZ288L3RpdGxlPjxnIGlkPSJMYXllcl8xIiBkYXRhLW5hbWU9IkxheWVyIDEiPjxjaXJjbGUgY2xhc3M9ImNscy0xIiBjeD0iNTAiIGN5PSI1MCIgcj0iNTAiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0yMC43MSA1MCkgcm90YXRlKC00NSkiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik04NS4zNiwxNC42NEE1MCw1MCwwLDAsMSwxNC42NCw4NS4zNloiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik02MC4xNyw0My4xM2EzLjQxLDMuNDEsMCwwLDEsLjA3LjY4QTMuNCwzLjQsMCwwLDAsNjAuMTcsNDMuMTNaIi8+PHBhdGggY2xhc3M9ImNscy0zIiBkPSJNNTkuMjEsNDEuMzhBMy40OCwzLjQ4LDAsMCwxLDYwLDQyLjQ3LDMuNDgsMy40OCwwLDAsMCw1OS4yMSw0MS4zOFoiLz48cG9seWdvbiBjbGFzcz0iY2xzLTMiIHBvaW50cz0iNTkuMTMgNDEuMjkgNTkuMTMgNDEuMjkgNTkuMDQgNDEuMjEgNTkuMTMgNDEuMjkiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik01OS4xMiw0Ni4zNCwzMy41NCw2OS43M2wyNS41OC0yMy40YTMuNDUsMy40NSwwLDAsMCwuOTEtMS40QTMuNDUsMy40NSwwLDAsMSw1OS4xMiw0Ni4zNFoiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik0yOC41NCw3MS40OCw1OC44Nyw0MSw1OC43OSw0MWEzLjcsMy43LDAsMCwwLTUuMjEuMkwyOSw2OC4yNmMtMSwxLTEuMTksMi41Mi0uMzUsMy4zMWExLjc1LDEuNzUsMCwwLDAsLjc0LjQxLDEuNzUsMS43NSwwLDAsMS0uNzQtLjQxWiIvPjxwYXRoIGNsYXNzPSJjbHMtNCIgZD0iTTI4LjYyLDcxLjU3QTIuNTIsMi41MiwwLDAsMCwzMiw3MS4xMUw1OS4xMiw0Ni4zNGEzLjQyLDMuNDIsMCwwLDAsMC01TDU4Ljg3LDQxLDI4LjU0LDcxLjQ4WiIvPjxwYXRoIGNsYXNzPSJjbHMtNSIgZD0iTTM0LjQ2LDM0LjcxbC0xMC42LTguNDNhMi42LDIuNiwwLDAsMC00LjIsMi4zM2wuMTksMS42NGExOC4yMSwxOC4yMSwwLDAsMCwxMS42OSwxNWwxMy42OSw1LjE0LDIuMzEtMi41NUwzNi4xNiwzNi43M0ExNi40NSwxNi40NSwwLDAsMSwzNC40NiwzNC43MVoiLz48cGF0aCBjbGFzcz0iY2xzLTUiIGQ9Ik03NC42OSw3NS40MSw2NS44OCw2NS4xMmExNi40NSwxNi40NSwwLDAsMS0yLjA4LTEuNjNMNTIuMzMsNTIuNTVsLTIuNTIsMi4zLDUuNjcsMTMuNThBMTguMjEsMTguMjEsMCwwLDAsNzAuODcsNzkuNTZsMS42NC4xM0EyLjYsMi42LDAsMCwwLDc0LjY5LDc1LjQxWiIvPjxwYXRoIGNsYXNzPSJjbHMtNSIgZD0iTTU4LjY0LDQ2Ljc4YTMsMywwLDAsMCwzLjg1LTIuMTcsMy4yOCwzLjI4LDAsMCwwLTMtNC4xNWgwbC0uNTkuNTloMGwuMjYuMjVhMy40MiwzLjQyLDAsMCwxLDAsNVoiLz48cGF0aCBjbGFzcz0iY2xzLTYiIGQ9Ik0zMi43NywxNy4xOGwtLjUsMS41M2ExNy42LDE3LjYsMCwwLDAsMy44OSwxOEw0Ny41Myw0Ny44MmwzLjYxLTQtMTMuNy0yN0EyLjU0LDIuNTQsMCwwLDAsMzIuNzcsMTcuMThaIi8+PHBhdGggY2xhc3M9ImNscy02IiBkPSJNODMuNjUsNjEuNDgsNTYuMzUsNDguODdsLTQsMy42OEw2My44LDYzLjQ5YTE3LjYsMTcuNiwwLDAsMCwxOC4xNSwzLjIzbDEuNTEtLjU1QTIuNTQsMi41NCwwLDAsMCw4My42NSw2MS40OFoiLz48cGF0aCBjbGFzcz0iY2xzLTYiIGQ9Ik01My41OCw0MS4xN2EzLjcsMy43LDAsMCwxLDUuMjEtLjJsLjA4LjA4aDBsLjU5LS41OWgwYTMuNDEsMy40MSwwLDAsMC00LjI5LTIuOTNjLTIsLjM4LTMuMDcsMi42OC0yLDQuMTFaIi8+PC9nPjwvc3ZnPg==
  introduction: >-
    **JBoss EAP 7 is built to provide simplified deployment and full Jakarta EE compliance for applications in any environment**. Whether on-premise or in virtual, private, public, and hybrid clouds, JBoss EAP features a modular architecture that starts services only as they are required. The extreme low memory footprint and fast startup times mean that JBoss EAP is ideal for environments where efficient resource utilization is a priority, such as Red Hat OpenShift.

    - **Optimized for OpenShift, Cloud and Containers**: JBoss EAP gives additional packaging options that allows users to reduce disk and memory footprint to provide just enough runtime for your application workloads.

    - **Jakarta EE 8 compatibility-lightweight flexible architecture**: JBoss EAP 7 is a Jakarta EE 8 compatible application server runtime.

    - **Red Hat Portfolio Integration**: Fully supported integration with the rest of the Red Hat ecosystem makes Red Hat JBoss EAP 7 an ideal platform to use for DevOps.

    - **More productive developers with DevOps and Agile Development**: Red Hat JBoss EAP 7 can be adopted in agile and DevOps processes. JBoss EAP allows developers to meet line-of-business demands.

  tasks:
    - description: >-
        To create a JBoss EAP 7 application:
        
        1. Click on the [perspective switcher]{{highlight qs-perspective-switcher}} at the top of the navigation, and select **Developer**.
        
        1. In the navigation menu, click [Add]{{highlight qs-nav-add}}.
                        
        1. On the **+Add** page, click **Helm Chart**. 
        
        1. In the Helm Chart catalog, click the **JBoss EAP 7.4** tile.
        
            - The side panel displays information about the JBoss EAP 7 chart
        
        1. Click **Install Helm Chart**
        
            - Some form sections are collapsed by default. No changes to these sections are needed to proceed. Click the accordion above a collapsed section to expand and view its content.
        
        1. At the bottom of the form, click **Install** to create the JBoss EAP 7 application using the Helm Chart.
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: |-
          The Helm Release is represented by the light grey shape with a darker grey dashed border.  The deployment is a white circle containing the JBoss EAP logo.  Verify the application was successfully created:
          
          - Do you see a **eap74** Helm Release?
          
          - Do you see a **eap74** deployment?

      summary:
        failed: Try the steps again.
        success: Your JBoss EAP7 application has been deployed onto OpenShift.
      title: Create a JBoss EAP7 application with Helm
    - description: >-
        The Helm release can be displayed to see all resources that were created when the JBoss EAP 7 application is deployed.
        
        1. In the navigation menu, click [Helm]{{highlight qs-nav-helm}}.

        1. Click on the **eap74** Helm release
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: >-
          Verify you see the Helm release:

          - Do you see a **Deployed** badge next to the Helm Release **eap74**
      summary:
        failed: Try the steps again.
        success: Your Helm release for JBoss EAP 7 is deployed.
      title: View the Helm release
    - description: >-
        To view the build status of the JBoss EAP 7 application:
        
        1. In the navigation menu, click [Builds]{{highlight qs-nav-builds}}.

            - a JBoss EAP 7 application use a 2-step builds, the final build that contains the application is named **eap74**.

        1. Click on the **eap74** Build Config 

        1. The build is shown in the **Builds** tab and is named **eap74-2**.

            - this build will appear once a first intermediate build **eap74-build-artifacts-1** is complete which may take a few minutes.

            - a build will go in various stages that are shown in a badge next to the build name (**Pending, Running, Complete**)
      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: >-
          Verify the build is complete:

          - This build may take a few minutes. When it's finished, a **Complete** badge will surface on the page header beside build name **eap74-2**. Did this badge appear?

      summary:
        failed: Try the steps again.
        success: Your build is complete.
      title: View the Build status
    - description: >-
        To view the pod status:

        1. In the navigation menu, click [Topology]{{highlight qs-nav-topology}}.
        
        1. Hover over the pod donut to see the pod status in a tooltip.

              - Notice that the **eap74** deployment has a pod donut imposed on the circle, representing the pod status.  

              - The color of the donut indicates the pod status (light blue = **Pending**, blue = **Not Ready**, dark blue = **Running**)

      review:
        failedTaskHelp: >-
          This task isn’t verified yet. Try the task again.
        instructions: |-
          Verify you see the pod status:
          
          - Do you see the number of associated pods and their statuses?

      summary:
        failed: Try the steps again.
        success: Your deployment has one running pod.
      title: View the pod status
    - description: >-

        The external link icon on the top right quadrant of the **eap74** deployment represents the route URL.  
        
        1. Click on the external link icon to open the URL and run the application in a new browser tab.

      review:
        failedTaskHelp: This task isn’t verified yet. Try the task again.
        instructions: >-
          Verify your JBoss EAP 7 application is running:

          - Does the new tab displays **Hello World!**?
      summary:
        failed: Try the steps again.
        success: Your JBoss EAP 7 application is running.
      title: Run the JBoss EAP 7 application
  conclusion: >-
    Your JBoss EAP 7 application is deployed and ready.

     Learn more about [JBoss EAP](https://www.redhat.com/en/technologies/jboss-middleware/application-platform).